/* Self-host the site fonts (Amiri + Inter) so pages stop render-blocking on
   two cross-origin Google Fonts requests and typography works fully offline.
   Downloads the woff2 subsets we actually use (Amiri: arabic+latin, Inter:
   latin), writes fonts/font-N.woff2 + css/fonts.css. Run once; re-run only to
   change families/weights. */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const CSS_URL = "https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;600;700&display=swap";
const KEEP = { Amiri: ["arabic", "latin"], Inter: ["latin"] };

(async () => {
  const css = await fetch(CSS_URL, { headers: { "User-Agent": UA } }).then(r => r.text());
  // css2 emits "/* subset */ @font-face { ... }" blocks in order
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]+\})/g)]
    .map(m => ({ subset: m[1], block: m[2] }));
  let out = "/* generated by scripts/fetch-fonts.js — self-hosted Amiri + Inter */\n";
  let n = 0, kept = 0;
  fs.mkdirSync(path.join(ROOT, "fonts"), { recursive: true });
  for (const { subset, block } of blocks) {
    const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    if (!fam || !(KEEP[fam] || []).includes(subset)) continue;
    const url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!url) continue;
    n++;
    const name = `font-${n}.woff2`;
    const buf = Buffer.from(await fetch(url, { headers: { "User-Agent": UA } }).then(r => r.arrayBuffer()));
    if (buf.length < 1000) throw new Error("suspiciously small font file from " + url);
    fs.writeFileSync(path.join(ROOT, "fonts", name), buf);
    out += `/* ${fam} ${subset} */\n` + block.replace(/url\(https:[^)]+\)/, `url(../fonts/${name})`) + "\n";
    kept++;
  }
  if (kept < 6) throw new Error("expected at least 6 font faces, got " + kept);
  fs.writeFileSync(path.join(ROOT, "css", "fonts.css"), out, "utf8");
  const total = fs.readdirSync(path.join(ROOT, "fonts")).reduce((a, f) => a + fs.statSync(path.join(ROOT, "fonts", f)).size, 0);
  console.log(`wrote css/fonts.css + ${kept} woff2 files (${Math.round(total / 1024)} KB)`);
  console.log("font files:", fs.readdirSync(path.join(ROOT, "fonts")).join(", "));
})();
